language: java
script: ./gradlew build
deploy:
  - provider: script
    script: ./gradlew -Pversion=$TRAVIS_TAG bintrayUpload
    skip_cleanup: true
    on:
      repo: jossemarGT/cookie-twist
      branch: master
      tags: true
  - provider: releases
    api_key: $GH_TOKEN
    skip_cleanup: true
    file_glob: true
    file: build/libs/*.jar
    on:
      repo: jossemarGT/cookie-twist
      branch: master
      tags: true
